site_name: EGR314 Team 204 Website 
site_url: https://asu-egr314-2025-s-204.github.io/
repo_url: https://github.com/ASU-EGR314-2025-S-204/ASU-EGR314-2025-S-204.github.io
edit_uri: edit/main/docs/

nav:
  - index.md
  - Team Organization:
    - Team_Organization/index.md
    - Team Charter: Team_Organization/teamcharter.md
    - Product Mission Statement: Team_Organization/Product_Mission_Statement.md
  - Ideation and Concept Generation:
    - Concept_Ideation/index.md
    - Articles: Concept_Ideation/Articles.md
    - Product Overview: Concept_Ideation/Productoverview.md
    - Product Concepts Brainstorming: Concept_Ideation/ProductConceptsBrainstorming.md
    - Presentation Video: Concept_Ideation/PresentationVideo.md
  - appendix.md
  

theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
  logo: static/logo.svg
  favicon: static/logo.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
#    - navigation.expand
#    - navigation.instant # doesn't work that well

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static
  
copyright: "Copyright &copy; 2025 Team 204"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2023_fall
      name: 2023 Sit